HakatonIKTIB/Models/ErrorViewModel.cs
namespace HakatonIKTIB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HakatonIKTIB/Models/RegisterModel.cs
using System.ComponentModel.DataAnnotations;

namespace HakatonIKTIB.Models
{
    public class RegisterModel
    {
        [Required(ErrorMessage = "Введите логин")]
        public string Login { get; set; }
        [Required(ErrorMessage = "Введите пароль")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Подтвердите пароль")]
        public string ConfrimPassword { get; set; }
        [Required(ErrorMessage = "Введите имя")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Введите Фамилию")]
        public string LastName { get; set; }
        public string SurName { get; set; }
        public int Course {  get; set; }
        public string Specialization { get; set; }
        public string University { get; set; }
    }
}

HakatonIKTIB/Models/UserModel.cs
using HakatonIKTIB.Classes;
using System.ComponentModel.DataAnnotations;

namespace HakatonIKTIB.Models
{
    public class UserModel
    {
        public UserModel()
        {
            user = null;
        }

        public UserModel(User user)
        {
            this.user = user;
        }

        public UserModel(Discussion discussion)
        {
            this.discussion = discussion;
            user = null;
        }

        public UserModel(Discussion discussion, User user)
        {
            this.discussion = discussion;
            this.user = user;
        }

        public Discussion? discussion { get; }
        public User? user { get; }

        [Required]
        public string ApplicantId { get; set; }
        [Required]
        public string Topic { get; set; }
        [Required]
        public string Text { get; set; }

        [Required]
        public string AnswerDiscussionId { get; set; }
        [Required]
        public string AnswerUserId { get; set; }
        [Required]
        public string AnswerText { get; set; }
    }
}

HakatonIKTIB/Controllers/DiscussionsController.cs
using HakatonIKTIB.Classes;
using HakatonIKTIB.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HakatonIKTIB.Controllers
{
    public class DiscussionsController : Controller
    {
        // GET: DiscussionPageController
        public IActionResult Index(ulong discussionId, ulong userId)
        {
            Discussion? discus = DataBase.GetDiscussionById(discussionId);
            UserModel model = new();
            if (userId == 0)
            {
                model = new(discus);
                return View(model);
            }

            User? user = DataBase.GetUserById(userId);
            model = new(discus, user);
            return View(model);
        }

        [HttpGet]
        public IActionResult CreateDiscussion(ulong userId)
        {
            User? user = DataBase.GetUserById(userId);
            UserModel model = new(user);
            return View(model);
        }

        [HttpPost]
        public IActionResult CreateDiscussion(string applicantId, string topic, string text)
        {
            ulong userId = ulong.Parse(applicantId);
            DataBase.CreateDiscussion(userId, topic, text);
            return RedirectToAction("Index", "Home", new { userId } );
        }

        [HttpGet]
        public IActionResult AddAnswer(ulong discussionId, ulong userId) => RedirectToAction("Index", "Discussions", new { discussionId, userId });

        [HttpPost]
        public IActionResult AddAnswer(string answerDiscussionId, string answerUserId, string answerText)
        {
            ulong discussionId = ulong.Parse(answerDiscussionId);
            ulong userId = ulong.Parse(answerUserId);
            DataBase.AddAnswer(discussionId, userId, answerText);
            UserModel model = new(DataBase.GetDiscussionById(discussionId), DataBase.GetUserById(userId));
            return RedirectToAction("Index", "Discussions", new { discussionId, userId });
        }
    }
}

HakatonIKTIB/Controllers/HomeController.cs
using System.Diagnostics;
using HakatonIKTIB.Models;
using Microsoft.AspNetCore.Mvc;
using HakatonIKTIB.Classes;

namespace HakatonIKTIB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index(ulong userId)
        {
            if (userId == 0)
            {
                return View(new UserModel());
            }
            else
            {
                return View(new UserModel(DataBase.GetUserById(userId)));
            }
        }

        public IActionResult FAQ()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HakatonIKTIB/Controllers/UserPageController.cs
using HakatonIKTIB.Models;
using HakatonIKTIB.Classes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HakatonIKTIB.Controllers
{
    public class UserPageController : Controller
    {
        // GET: UserPage
        public IActionResult Index(string login, string password)
        {
            UserModel model = new(DataBase.Login(login, password));
            return View(model);
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Regiser() => View();

        [HttpPost]
        public async Task<IActionResult> Regiser(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                ulong userId = DataBase.Register(model.Login, model.Password, model.Name, model.LastName, model.SurName, model.Course, model.Specialization, model.University , out string s).Id;
                return RedirectToAction(actionName: "Index", controllerName: "Home", new { userId });
            }

            return View();
        }

        [HttpGet]
        public IActionResult Login() => View();

        [HttpPost]
        public IActionResult Login(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                ulong userId = DataBase.Login(model.Login, model.Password).Id;
                return RedirectToAction(actionName: "Index", controllerName: "Home", new { userId });
            }

            return View();
        }
    }
}

HakatonIKTIB/Views/Discussions/CreateDiscussion.cshtml
@model UserModel
@{
    ViewData["Title"] = "Настаник - создание обсуждения";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/discussion.css" />
</head>
<body>
    <form asp-action="CreateDiscussion" asp-controller="Discussions" method="post">
        @{
            Model.ApplicantId = Model.user.Id + "";
        }
        <input class="input" asp-for="ApplicantId" type="hidden" value="@Model.ApplicantId" />
        <h1>Тема</h1>
        <input class="input" asp-for="Topic" type="text" />
        <h1>Текст</h1>
        <input class="input" asp-for="Text" type="text" />
        <button type="submit">Создать обсуждение</button>
    </form>
</body>

HakatonIKTIB/Views/Discussions/Index.cshtml
@model UserModel
@using HakatonIKTIB.Classes

@{
    ViewData["Title"] = "Наставник - " + Model.discussion.Topic;
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/discussion.css" />
</head>
<body>
    <div id="Topic">
        <h1>@Model.discussion.Topic</h1>
        <h3>@Model.discussion.Text</h3>
        <h6>@DataBase.GetUserNameById(Model.discussion.ApplicantId)</h6>
    </div>
    @{
        if (Model.user != null)
        {
            <div id="addanswer">
                @{
                    ulong discussionId = Model.discussion.Id;
                    ulong userId = Model.user.Id;
                    userId = Model.user.Id;
                }
                <form asp-action="AddAnswer" asp-controller="Discussions" method="post">
                <input type="hidden" asp-for="AnswerDiscussionId" value="@discussionId" />
                <input type="hidden" asp-for="AnswerUserId" value="@userId" />
                <label>Ответ</label>
                <input type="text" asp-for="AnswerText" />
                <button type="submit">Ответить</button>
            </form>
        </div>
        }
    }
    @{
        var answers = DataBase.GetAnswersByDiscussionId(Model.discussion.Id);

        for (int i = 0; i < answers.Count; i++)
        {
            <div class="answer">
                <h3>@answers[i].Text</h3>
                <h3>@DataBase.GetUserNameById(answers[i].UserId)</h3>
            </div>
        }
    }
</body>

HakatonIKTIB/Views/Home/FAQ.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

HakatonIKTIB/Views/Home/Index.cshtml
@model UserModel
@using HakatonIKTIB.Classes;
@{
    ViewData["Title"] = "Наставник - главная страница";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/home.css" />
</head>
<body>
    <div class="main">
        <div id="popular" class="boxes">
            <h1>Популярное</h1>
        </div>
        <div id="intresting" class="boxes">
            <h1>Интересно для вас</h1>
            @{
                if (Model != null)
                {
                    if (Model.user != null)
                    {
                        if (Model.user.Tags != null)
                        {
                            if (Model.user.Tags.Count > 0)
                            {
                                List<Discussion> discussions = DataBase.GetDiscussionsByTagId(Model.user.Tags[0].Id, false);
                                int maxI = discussions.Count >= 7 ? 7 : discussions.Count;
                                Console.WriteLine(discussions.Count);

                                for (int i = 0; i < maxI; i++)
                                {
                                    <div class="topics">
                                        <h3>@discussions[i].Topic</h3>
                                        <h5>@discussions[i].Text</h5>
                                    </div>
                                }
                            }
                        }
                    }
                }
            }
        </div>
        <div class="boxes">
            <h1>Ваши обсуждения</h1>
            @{
                if (Model != null)
                {
                    if (Model.user != null)
                    {
                        if (Model.user.ActiveDiscussions != null)
                        {
                            int maxI = Model.user.ActiveDiscussions.Count >= 7 ? 7 : Model.user.ActiveDiscussions.Count;
                            Console.WriteLine(Model.user.ActiveDiscussions.Count);

                            for (int i = 0; i < maxI; i++)
                            {
                                ulong discussionId = Model.user.ActiveDiscussions[i].Id;

                                <div class="topics">
                                    <h3>@Html.ActionLink($"{Model.user.ActiveDiscussions[i].Topic}", "Index", "Discussions", new { discussionId, Model.user.Id })</h3>
                                    <h5>@Model.user.ActiveDiscussions[i].Text</h5>
                                </div>
                            }
                        }
                    }
                }
            }
        </div>
        <div class="boxes">
            <h1>Новые</h1>
            @{
                if (Model != null)
                {
                    List<Discussion> lastDiscuissons = DataBase.GetlastDescutions();

                    if (lastDiscuissons != null)
                    {
                        if (lastDiscuissons.Count > 0)
                        {
                            ulong userId = 0;

                            if (Model != null)
                                if (Model.user != null)
                                    userId = Model.user.Id;

                            for (int i = 0; i < lastDiscuissons.Count; i++)
                            {
                                ulong discussionId = lastDiscuissons[i].Id;

                                <a herf="/Discussions/Index/?discussionId=@lastDiscuissons[i].Id&userId=@userId">
                                    <div class="topics">
                                        <h3>@Html.ActionLink(lastDiscuissons[i].Topic, "Index", "Discussions", new { discussionId, userId })</h3>
                                        <h5>@lastDiscuissons[i].Text</h5>
                                    </div>
                                </a>
                            }
                        }
                    }
                }
            }
        </div>
    </div>
</body>

HakatonIKTIB/Views/Shared/MainPanel.cshtml
@model UserModel

<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="header">
        <div id="site">
            Название
        </div>
        <div id="panel">
            <div class="roundedbutton">
                @{
                    ulong userId = 0;
                    if (Model != null)
                    {
                        if (Model.user != null)
                        {
                            userId = Model.user.Id;
                            @Html.ActionLink("/\\", "Index", "Home", new { userId });
                        }
                        else
                        {
                            @Html.ActionLink("/\\", "Index", "Home", new { userId });
                        }
                    }
                    else
                    {
                        @Html.ActionLink("/\\", "Index", "Home", new { userId });
                    }
                }
            </div>
            <div id="searchfield">
                Поиск
            </div>
            <div class="roundedbutton">
                Поиск
            </div>
            <div class="roundedbutton">
                FAQ
            </div>
            <div class="roundedbutton">
                @{
                    if (Model != null)
                    {
                        if (Model.user != null)
                        {
                            userId = Model.user.Id;
                            @Html.ActionLink("+", "CreateDiscussion", "Discussions", new { userId })
                        }
                        else
                        {
                            @Html.ActionLink("+", "Register", "UserPage", new { userId })
                        }
                    }
                    else
                    {
                        @Html.ActionLink("+", "Register", "UserPage", new { userId })
                    }
                }
            </div>
        </div>
        @{
            bool registered = false;

            if (Model != null) {
                if (Model.user != null) {
                    registered = true;
                }

                if (registered)
                {
                    <div id="user">
                        @Html.ActionLink(Model.user.LastName, "Index", "UserPage", new { Model.user.Login, Model.user.Password })
                    </div>
                }
                else
                {
                    <a asp-controller="UserPage" asp-action="Register">
                        <div id="user">
                            <b>Войти</b>
                        </div>
                    </a>
                }
            }
        }
    </div>

    @RenderBody();
</body>

HakatonIKTIB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HakatonIKTIB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HakatonIKTIB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HakatonIKTIB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <p class="nav navbar-text">Hello, @User.Identity?.Name!</p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HakatonIKTIB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HakatonIKTIB/Views/UserPage/Index.cshtml
@model UserModel

@{
    ViewData["Title"] = $"Наставник - вы: {Model.user.Name}";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <h1>@Model.user.LastName</h1>
</body>

HakatonIKTIB/Views/UserPage/Register.cshtml
@model RegisterModel

@{
    ViewData["Title"] = "Наставник - вход";
}

<head>
    <link rel="stylesheet" href="~/css/register.css" />
</head>
<body>
    <form class="main" asp-action="Regiser" asp-controller="UserPage" method="post">
        <h1>Регистрация</h1>
        <div class="datainput">
            <label>*Логин</label>
            <input type="text" asp-for="Login" class="input" />
        </div>
        <div class="datainput">
            <label>*Пароль</label>
            <input type="text" asp-for="Password" class="input" />
        </div>
        <div class="datainput">
            <label>*Подтвердите пароль</label>
            <input type="text" asp-for="ConfrimPassword" class="input" />
        </div>
        <div class="datainput">
            <label>*Имя</label>
            <input type="text" asp-for="Name" class="input" />
        </div>
        <div class="datainput">
            <label>*Фамилия</label>
            <input type="text" asp-for="LastName" class="input" />
        </div>
        <div class="datainput">
            <label>Отчество</label>
            <input type="text" asp-for="SurName" class="input" />
        </div>
        <div class="datainput">
            <label>Курс</label>
            <input type="text" asp-for="Course" class="input" />
        </div>
        <div class="datainput">
            <label>Специальность</label>
            <input type="text" asp-for="Specialization" class="input" />
        </div>
        <div class="datainput">
            <label>Университет</label>
            <input type="text" asp-for="University" class="input" />
        </div>
        <button type="submit">Зарегистрировалться</button>
    </form>
    <form class="main" asp-action="Login" asp-controller="UserPage" method="post">
        <h1>Вход</h1>
        <div class="datainput">
            <label>*Логин</label>
            <input type="text" asp-for="Login" class="input" />
        </div>
        <div class="datainput">
            <label>*Пароль</label>
            <input type="text" asp-for="Password" class="input" />
        </div>
        <button type="submit">Войти</button>
    </form>
</body>